### PR TITLE
fix(GoveeErrors namespace): Import GoveeError from `govee_api_laggat`

### PR DESCRIPTION
**Pull request by wwelles**

### CODE REVIEW

**Comment by wwelles** [comment]
@LaggAt custom component wasn't working, this fixed it for me.

Running: HA 2023.06 via docker compose

**Comment by DAE51D** [comment]
Can someone please approve and merge this to fix it for the rest of us?

**Review by DAE51D — APPROVED** [review]

**Comment by wwelles** [comment]
@LaggAt any way you could kindly merge?

**Comment by LaggAt** [comment]
Thanks.

**Pull request merged**
